# Introducción a la librería de Numpy.

--------

### Data Fundamentals con Python

#### Enero 2023

**Aurora Cobo Aguilera**

**The Valley**

--------




En este notebook, introduciremos una librería básica de cálculo científico, *numpy*.


In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

## 1. Uso de la librería Numpy y matrices

El módulo _numpy_ es muy útil para cálculo científico en python.

La principal estructura de datos en _numpy_ es el array con N dimensiones. 

### 1.1. Matrices con Numpy

En Numpy una matriz se representa a través de un array de 2 dimensiones.

Puedes definir un _numpy_ _array_ a partir de una lista o una lista de listas. Python intentará construirlo con las dimensiones apropiadas. Puedes consultar las dimensiones con _shape()_


In [ ]:
my_array = np.array([[1, 2], [3, 4]])
print(my_array)
print(np.shape(my_array)) #checking the dimensions

[[1 2]
 [3 4]]
(2, 2)


**Ejercicio**: Define un nuevo array de 3x2 llamado *my_array2* con  [1, 2, 3] en la primera fila y [4,5,6] en la segunda.
Consulta las dimensiones del array.


In [ ]:
#<SOL>
my_array2 = np.array([[1,2,3],[4,5,6]])
print(my_array2)
print(np.shape(my_array2))
#<SOL>

[[1 2 3]
 [4 5 6]]
(2, 3)


Hay un número de operaciones que puedes hacer con arrays numpy. Una de las más importantes es **slicing**, que consiste en extraer un subarray de un array.

In [ ]:
my_array3 = my_array[:, 1] #de todas las filas coge la columna numero 1
print(my_array3)
print(my_array[1, 0:2]) #de la fila 1 printea las columnas de la 0 a la 2 (no incluida la dos)

[2 4]
[3 4]


Algo importante a considerar cuando haces slicing son las dimensiones del array de salida. Consulta las dimensiones de *my_array3*. Consulta tambien sus dimensiones con la función _ndim_:




In [ ]:
print(np.shape(my_array3))
#help(np.ndarray.ndim)
print(my_array3.ndim)

(2,)
1


Si lo has calculado correctamente, verás que *my_array3* es de 1 dimensión. Esto puede ser un problema cuando trabajas con matrices de 2 dimensiones (y con vectores que se consideran de 2D con uno de los tamaños igual a 1). Para resolver esto, _numpy_ proporciona la constante _newaxis_.




In [ ]:
my_array3 = my_array3[:, np.newaxis] #hace de un vector de numeros, una matrix nx1

Consulta de nuevo la dimensión de *my_array3*.



In [ ]:
print(my_array3.ndim)
print(np.shape(my_array3))
print(my_array3)

2
(2, 1)
[[2]
 [4]]


Otro método importante de manipulación de array es _concatenation_ o _stacking_. Es útil para siempre declarar en qué dirección queremos apilar arrays. Por ejemplo, en la sigueinte celda apilamos verticalmente. 

In [ ]:
print(np.concatenate( (my_array, my_array2) , axis=1)) # columnwise concatenation

[[1 2 1 2 3]
 [3 4 4 5 6]]


Ejercicio: *Concatena* la primera columna de *my_array* y la segunda columna de *my_array2*

In [ ]:
#<SOL>
print(np.concatenate((my_array[:,0],my_array2[:,1])))
#<SOL>

[1 3 2 5]


Puedes crear _numpy_ arrays de diferentes formas, no sólo a partir de listas. Por ejemplo _numpy_ proporciona un número de funciones para crear tipos especiales de matrices.

**Ejercicio**: Crea 3 arrays usando _ones_, _zeros_ and _eye_. Si tienes alguna duda sobre los parámetros de las funciones, mira en la ayuda con la función _help( )_.

In [ ]:
#<SOL>
# Crear un array de unos
array_ones = np.ones((3, 3))
print("Array de unos:")
print(array_ones)
print()

# Crear un array de ceros
array_zeros = np.zeros((2, 4))
print("Array de ceros:")
print(array_zeros)
print()

# Crear una matriz identidad
matriz_identidad = np.eye(4)
print("Matriz identidad:")
print(matriz_identidad)
#<SOL>

Array de unos:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriz identidad:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Además _numpy_ ofrece todas las operaciones básicas con matrices: multiplicaciones, producto escalar, ...
Puedes encontrar información sobre ellas en [Numpy manual](https://numpy.org/doc/stable/user/) 



#### 1.1.1. Suma de matrices

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


#### 1.1.2. Resta de matrices

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(np.shape(A))
B = np.array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]])
print(B)
print(np.shape(B))
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
(2, 3)
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


#### 1.1.3. Multiplicación de matrices (element-wise)

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


#### 1.1.4. División de matrices

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


#### 1.1.5. Producto escalar de matrices

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
B = np.array([[1, 2], [3, 4]])
print(B)
C = A.dot(B)
print(C)

#### 1.1.6. Producto de matrices y vectores

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
B = np.array([0.5, 0.5])
print(B)
C = A.dot(B)
print(C)
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]
[1.5 3.5 5.5]


#### 1.1.7. Producto de matrices y escalares

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
b = 0.5
print(b)
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


#### 1.1.8. Matriz transpuesta

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


#### 1.1.9. Matriz inversa

In [ ]:
from numpy.linalg import inv
# define matrix
A = np.array([[1.0, 2.0], [3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


Además de _numpy_ hay librerías más avanzadas para cálculos científicos, _scipy_. [Scipy](https://docs.scipy.org/doc/scipy/) incluye módulos para álgebra lineal, procesado de la señal, transformadas de Fourier, ...